/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.form.Home.Header;

import controller.Functional.Functional;
import javax.swing.ImageIcon;

/**
 *
 * @author LENOVO
 */
public class Header extends javax.swing.JPanel {

    /**
     * Creates new form Header
     */
    public Header() {
        initComponents();
        addComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logo = new javax.swing.JLabel();
        backBtn = new javax.swing.JLabel();
        menuBtn = new javax.swing.JLabel();
        notiBtn = new javax.swing.JLabel();
        personalImg = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        logo.setBackground(new java.awt.Color(255, 51, 51));
        logo.setForeground(new java.awt.Color(255, 51, 51));
        logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo.setText("logo");
        logo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        logo.setSize(54, 54);

        backBtn.setToolTipText("");
        backBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backBtn.setMaximumSize(new java.awt.Dimension(25, 25));
        backBtn.setPreferredSize(new java.awt.Dimension(25, 25));
        backBtn.setSize(25,25);

        menuBtn.setText(" ");
        menuBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuBtn.setMaximumSize(new java.awt.Dimension(25, 25));
        menuBtn.setMinimumSize(new java.awt.Dimension(0, 0));
        menuBtn.setSize(25,25);

        notiBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        notiBtn.setSize(25, 25);

        personalImg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        personalImg.setText("img");
        personalImg.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        personalImg.setSize(54, 54);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(menuBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 621, Short.MAX_VALUE)
                .addComponent(notiBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(personalImg, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(menuBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(notiBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(9, 9, 9)))
            .addComponent(personalImg, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backBtn;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel menuBtn;
    private javax.swing.JLabel notiBtn;
    private javax.swing.JLabel personalImg;
    // End of variables declaration//GEN-END:variables

    private void addComponents() {
        String urlLogo = "/img/vng.jpg";
        String urlBack = "/img/back-button.png";
        String urlMenu = "/img/menu.png";
        String urlNoti = "/img/bell.png";

        ImageIcon iconLogo = Functional.scaleImg(logo, urlLogo);
        ImageIcon iconBack = Functional.scaleImg(backBtn, urlBack);
        ImageIcon iconMenu = Functional.scaleImg(menuBtn, urlMenu);
        ImageIcon iconNoti = Functional.scaleImg(notiBtn, urlNoti);

        logo.setIcon(iconLogo);
        backBtn.setIcon(iconBack);
        menuBtn.setIcon(iconMenu);
        notiBtn.setIcon(iconNoti);
    }
}
