/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.component.EmployeeBasicInfo;

import java.awt.BorderLayout;
import view.component.EmployeeBasicInfo.EmployeeInfo.EmployeeInfo_Component;

/**
 *
 * @author LENOVO
 */
public class EmployeeBasicInfo_Component extends javax.swing.JPanel {

    private EmployeeInfo_Component employeeInfo_Component;
    private static EmployeeBasicInfo_Component instance;

    public EmployeeBasicInfo_Component() {
        initComponents();
        initData();
        setLayout();
        addComponents();
    }

    public static EmployeeBasicInfo_Component getInstance() {
        if (instance == null) {
            instance = new EmployeeBasicInfo_Component();
        }
        return instance;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void setLayout() {
        this.setLayout(new BorderLayout());
    }

    private void addComponents() {
        this.add(new Header(), BorderLayout.NORTH);
        this.add(employeeInfo_Component, BorderLayout.CENTER);
    }

    private void initData() {
        employeeInfo_Component = EmployeeInfo_Component.getInstance();
    }

    public EmployeeInfo_Component getEmployeeInfo_Component() {
        return employeeInfo_Component;
    }

    public void setEmployeeInfo_Component(EmployeeInfo_Component employeeInfo_Component) {
        this.employeeInfo_Component = employeeInfo_Component;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
