/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.component.JobInfoDetail_Component;

import java.awt.Dimension;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author user
 */
public class Hotline extends javax.swing.JPanel {

    /**
     * Creates new form Hotline
     */
    public Hotline() {
        initComponents();
        this.setPreferredSize(new Dimension(900, 250));
        setImg();
    }

    private ImageIcon scaleImg(JLabel jLabel, String url) {
        hotline.setSize(20, 20);
        ImageIcon imageIcon = new ImageIcon(getClass().getResource(url));
        Image image = imageIcon.getImage();
        Image scaleImage = image.getScaledInstance(jLabel.getWidth(), jLabel.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(scaleImage);
        return scaledIcon;
    }

    private void setImg() {
        String urlPhone = "/img/Phone-icon.png";
        ImageIcon iconPhone = scaleImg(hotline, urlPhone);
        hotline.setIcon(iconPhone);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        hotline = new javax.swing.JLabel();
        email_CaNhan = new javax.swing.JLabel();
        input_EmailCaNhan = new javax.swing.JLabel();
        soDienThoai_CaNhan = new javax.swing.JLabel();
        input_SoDienThoaiCaNhan = new javax.swing.JLabel();
        diaChiThuongTru_CaNhan = new javax.swing.JLabel();
        input_DiaChiThuongTruCaNhan = new javax.swing.JLabel();
        diaChiTamTru_CaNhan = new javax.swing.JLabel();
        input_DiaChiTamTruCaNhan = new javax.swing.JLabel();
        email_CongTy = new javax.swing.JLabel();
        input_EmailCongTy = new javax.swing.JLabel();
        soDienThoai_CongTy = new javax.swing.JLabel();
        input_SoDienThoaiCongTy = new javax.swing.JLabel();
        diaChiCongTy = new javax.swing.JLabel();
        input_DiaChiCongTy = new javax.swing.JLabel();

        hotline.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        hotline.setForeground(new java.awt.Color(51, 51, 255));
        hotline.setText("Liên Hệ");

        email_CaNhan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        email_CaNhan.setText("Email cá nhân");

        input_EmailCaNhan.setText("jLabel2");

        soDienThoai_CaNhan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        soDienThoai_CaNhan.setText("Số điện thoại cá nhân");

        input_SoDienThoaiCaNhan.setText("jLabel2");

        diaChiThuongTru_CaNhan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        diaChiThuongTru_CaNhan.setText("Địa chỉ thường trú");

        input_DiaChiThuongTruCaNhan.setText("jLabel2");

        diaChiTamTru_CaNhan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        diaChiTamTru_CaNhan.setText("Địa chỉ tạm trú");

        input_DiaChiTamTruCaNhan.setText("jLabel2");

        email_CongTy.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        email_CongTy.setText("Email công ty");

        input_EmailCongTy.setText("jLabel2");

        soDienThoai_CongTy.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        soDienThoai_CongTy.setText("Số điện thoại công ty");

        input_SoDienThoaiCongTy.setText("jLabel2");

        diaChiCongTy.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        diaChiCongTy.setText("Địa chỉ công ty");

        input_DiaChiCongTy.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(hotline)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(input_EmailCaNhan)
                            .addComponent(email_CaNhan)
                            .addComponent(input_EmailCongTy)
                            .addComponent(email_CongTy))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 196, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(input_SoDienThoaiCaNhan)
                                    .addComponent(soDienThoai_CaNhan)))
                            .addComponent(input_SoDienThoaiCongTy)
                            .addComponent(soDienThoai_CongTy))
                        .addGap(223, 223, 223)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(input_DiaChiCongTy)
                                    .addComponent(diaChiCongTy))
                                .addContainerGap(382, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(input_DiaChiThuongTruCaNhan)
                                    .addComponent(diaChiThuongTru_CaNhan))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 193, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(input_DiaChiTamTruCaNhan)
                                    .addComponent(diaChiTamTru_CaNhan))
                                .addGap(84, 84, 84))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(hotline)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(email_CaNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(input_EmailCaNhan))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(soDienThoai_CaNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(input_SoDienThoaiCaNhan))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(diaChiThuongTru_CaNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(input_DiaChiThuongTruCaNhan))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(diaChiTamTru_CaNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(input_DiaChiTamTruCaNhan)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(email_CongTy, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(input_EmailCongTy))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(soDienThoai_CongTy, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(input_SoDienThoaiCongTy))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(diaChiCongTy, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(input_DiaChiCongTy)))
                .addGap(59, 59, 59))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel diaChiCongTy;
    private javax.swing.JLabel diaChiTamTru_CaNhan;
    private javax.swing.JLabel diaChiThuongTru_CaNhan;
    private javax.swing.JLabel email_CaNhan;
    private javax.swing.JLabel email_CongTy;
    private javax.swing.JLabel hotline;
    private javax.swing.JLabel input_DiaChiCongTy;
    private javax.swing.JLabel input_DiaChiTamTruCaNhan;
    private javax.swing.JLabel input_DiaChiThuongTruCaNhan;
    private javax.swing.JLabel input_EmailCaNhan;
    private javax.swing.JLabel input_EmailCongTy;
    private javax.swing.JLabel input_SoDienThoaiCaNhan;
    private javax.swing.JLabel input_SoDienThoaiCongTy;
    private javax.swing.JLabel soDienThoai_CaNhan;
    private javax.swing.JLabel soDienThoai_CongTy;
    // End of variables declaration//GEN-END:variables
}
