/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.component.LeaveApplication.ListLeaveRequest.BasicLeaveRequest;

import controller.Enum.Status;
import java.awt.Color;
import java.awt.Dimension;
import javax.swing.border.MatteBorder;

/**
 *
 * @author LENOVO
 */
public class BasicLeaveRequest_Component extends javax.swing.JPanel {

    /**
     * Creates new form BasicLeaveRequest_Component
     */
    public BasicLeaveRequest_Component(String type, String name, String date, String total, String status) {
        initComponents();
        customComponents();
        initData(type, name, date, total, status);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        type = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        total = new javax.swing.JLabel();
        status = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        type.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        type.setForeground(new java.awt.Color(0, 0, 0));
        type.setText("Nghỉ phép");

        name.setForeground(new java.awt.Color(0, 0, 0));
        name.setText("Lâm Quốc Nhân");

        date.setBackground(new java.awt.Color(0, 0, 0));
        date.setForeground(new java.awt.Color(102, 102, 102));
        date.setText("05/11/2024 - 06/11/2024");

        total.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        total.setForeground(new java.awt.Color(0, 0, 0));
        total.setText("2 ngày");

        status.setBackground(new java.awt.Color(102, 255, 0));

        javax.swing.GroupLayout statusLayout = new javax.swing.GroupLayout(status);
        status.setLayout(statusLayout);
        statusLayout.setHorizontalGroup(
            statusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 13, Short.MAX_VALUE)
        );
        statusLayout.setVerticalGroup(
            statusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 13, Short.MAX_VALUE)
        );

        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("LQN2005");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(type)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(total))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(name)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(date)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 121, Short.MAX_VALUE)
                        .addComponent(status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(type)
                    .addComponent(total))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(name)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(date))
                    .addComponent(status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel date;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel name;
    private javax.swing.JPanel status;
    private javax.swing.JLabel total;
    private javax.swing.JLabel type;
    // End of variables declaration//GEN-END:variables

    private void initData(String type, String name, String date, String total, String status) {
        this.type.setText(type);
        this.name.setText(name);
        this.date.setText(date);
        this.total.setText(total);
        this.status.setBackground(Status.valueOf(status.toUpperCase()).getColor());
    }

    private void customComponents() {
        this.setPreferredSize(new Dimension(280, 76));
        this.setBorder(new MatteBorder(0, 0, 1, 0, Color.GRAY));
    }
}
