/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.component.LeaveApplication.GridLeaveRequest.LeaveRequestForm;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Date;
import javax.swing.BorderFactory;
import javax.swing.border.Border;
import model.Employee;
import model.LeaveRequest;

/**
 *
 * @author LENOVO
 */
public class LeaveForm_Component extends javax.swing.JPanel {

    private Employee employee;
    private Date date;
    private Content content;
    private LeaveRequest leaveRequest;

    public LeaveForm_Component(LeaveRequest leaveRequest, Employee employee, Date date) {
        this.employee = employee;
        this.date = date;
        this.leaveRequest = leaveRequest;
        initComponents();
        initMyComponents(leaveRequest);
        customComponents();
    }

    public LeaveForm_Component() {
        initComponents();
        initMyComponents();
        customComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void customComponents() {
        this.setLayout(new FlowLayout(FlowLayout.CENTER, 0, 10));
        this.setPreferredSize(new Dimension(140, 60));
        Border lineBorder = BorderFactory.createLineBorder(Color.GRAY, 1);
        this.setBorder(lineBorder);
    }

    private void initMyComponents(LeaveRequest leaveRequest) {
        if (leaveRequest != null) {
            content = new Content(leaveRequest.getApproveStatus(), leaveRequest, employee, date);
            this.add(content);
        } else {
            content = new Content(4, leaveRequest, employee, date);
            this.add(content);

            this.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));

            this.addMouseListener(new MouseAdapter() {
                @Override
                public void mouseClicked(MouseEvent e) {
                    onClick();
                }
            });
        }
    }

    private void initMyComponents() {
        // Invalid Date
        this.setPreferredSize(new Dimension(140, 60));
        this.setBackground(new Color(227, 227, 227));
    }

    public Employee getEmployee() {
        return employee;
    }

    public void setEmployee(Employee employee) {
        this.employee = employee;
    }

    public Date getDate() {
        return date;
    }

    public void setDate(Date date) {
        this.date = date;
    }

    private void onClick() {
        content.openDetailForm();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
