/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.component.SelectEmployee;

import controller.Session.SharedData;
import javax.swing.JDialog;
import javax.swing.SwingUtilities;
import view.component.Manage_Component.ManageAttendance_Component;
import view.component.Manage_Component.ManageLeaveApplication_Component;
import view.component.Manage_Component.ManageSalary_Component;
import view.component.SelectEmployee.EmployeeInfo.PersonalInfo;

/**
 *
 * @author LENOVO
 */
public class Btn_Component extends javax.swing.JPanel {

    private String parentName;

    public Btn_Component() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        btn.setBackground(new java.awt.Color(69, 89, 190));
        btn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn.setForeground(new java.awt.Color(255, 255, 255));
        btn.setText("Đồng ý");
        btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActionPerformed
        JDialog parentDialog = (JDialog) SwingUtilities.getWindowAncestor(this);
        if (parentDialog != null) {
            parentDialog.dispose();
            switch (parentName) {
                case "ManageLeaveApplication_Component":
                    SharedData.getInstance().setEmployee_Leave(PersonalInfo.getInstance().getSelectedEmployee());
                    ManageLeaveApplication_Component.getInstance().getFilter().updateData();
                    break;
                case "ManageAttendance_Component":
                    SharedData.getInstance().setEmployee_Attendance(PersonalInfo.getInstance().getSelectedEmployee());
                    ManageAttendance_Component.getInstance().getkOW_Filter_Component().updateData();
                    break;
                case "ManageSalary_Component":
                    SharedData.getInstance().setEmployee_Salary(PersonalInfo.getInstance().getSelectedEmployee());
                    ManageSalary_Component.getInstance().getkOW_Filter_Component().updateData();
                    break;
                default:
                    System.out.println("Error in Btn SelecteEmployee");
            }
        }
    }//GEN-LAST:event_btnActionPerformed

    public String getParentName() {
        return parentName;
    }

    public void setParentName(String parentName) {
        this.parentName = parentName;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn;
    // End of variables declaration//GEN-END:variables
}
