/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.component.EmployeeBasicInfo.EmployeeInfo;

import java.awt.BorderLayout;
import javax.swing.JScrollPane;

/**
 *
 * @author LENOVO
 */
public class PersonalInfo extends javax.swing.JPanel {

    private JScrollPane content;
    private static PersonalInfo instance;

    public PersonalInfo() {
        initComponents();
        setLayout();
        addComponents();
    }

    public static PersonalInfo getInstance() {
        if (instance == null) {
            instance = new PersonalInfo();
        }
        return instance;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1120, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 473, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    private void setLayout() {
        this.setLayout(new BorderLayout());
    }

    private void addComponents() {
        this.add(new TitleEmployeeBasicInfo_Component(), BorderLayout.NORTH);

        content = new JScrollPane(PersonalInfo_Container.getInstance());
        content.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED);
        content.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
        content.setBorder(null);

        this.add(content, BorderLayout.CENTER);
    }

    public JScrollPane getContent() {
        return content;
    }

    public void setContent(JScrollPane content) {
        this.content = content;
    }

}
