/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.component.EmployeeBasicInfo.EmployeeInfo;

import controller.Functional.Functional;
import java.awt.BorderLayout;
import view.component.Infomation_Component.Status_Component;
import view.component.Infomation_Component.NameAndJob_Component;
import view.component.Infomation_Component.DateAndGender_Component;
import view.component.Infomation_Component.Contact_Component;
import java.awt.Color;
import java.awt.Dialog;
import java.awt.GridLayout;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.text.SimpleDateFormat;
import javax.swing.ImageIcon;
import javax.swing.JComponent;
import javax.swing.JDialog;
import javax.swing.SwingUtilities;
import javax.swing.border.MatteBorder;
import model.Employee;
import view.component.Manage_Component.ManageEmployeeDetailInfo_Component;
import view.component.Title_CheckBox.CheckBox_Component;

/**
 *
 * @author LENOVO
 */
public class PersonalBasicInfo_Container extends javax.swing.JPanel {

    private NameAndJob_Component nameAndJob;
    private DateAndGender_Component dateAndGender;
    private Status_Component status;
    private Contact_Component contact;
    private Employee employee;

    public PersonalBasicInfo_Container(Employee employee) {
        initComponents();
        this.employee = employee;
        setLayout();
        customComponents();
        addComponents(employee);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addComponents(Employee employee) {
        try {
            SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");

            String name = employee.getName();
            String employeeId = employee.getEmployeeId();
            String job = employee.getContracts().get(0).getJob().getProfession();
            String direct = employee.getDepartment().getName();
            ImageIcon img = Functional.convertByteArrayToIcon(employee.getImage());

            String place = employee.getContact().getPermanentAddress();
            String gender = employee.isGender() ? "Nam" : "Nữ";

            String dateOfBirth = dateFormat.format(employee.getDateOfBirth());

            String startDate = dateFormat.format(employee.getContracts().get(0).getJob().getStartDate());
            String senority = "";

            int sen = employee.getSenority();

            if (sen >= 30) {
                long months = sen / 30;
                senority = months + " tháng";
            } else {
                senority = sen + " ngày";
            }

            String type = employee.getContracts().get(0).getJob().getType();
            String email = employee.getContact().getPersonalEmail();
            String phone = employee.getContact().getPersonalPhone();

            nameAndJob = new NameAndJob_Component(name, employeeId, job, direct, img);
            dateAndGender = new DateAndGender_Component(dateOfBirth, place, gender);
            status = new Status_Component(startDate, senority, type);
            contact = new Contact_Component(email, phone, email);

            addMouseListenerToComponent(nameAndJob, "NameAndJob");
            addMouseListenerToComponent(dateAndGender, "DateAndGender");
            addMouseListenerToComponent(status, "Status");
            addMouseListenerToComponent(contact, "Contact");

            this.add(nameAndJob);
            this.add(dateAndGender);
            this.add(status);
            this.add(contact);
        } catch (Exception e) {
            System.out.println(this.getClass().getName() + e);
        }

    }

    private void setLayout() {
        this.setLayout(new GridLayout(1, 4, 0, 0));
    }

    private void customComponents() {
        this.setBorder(new MatteBorder(0, 0, 1, 0, Color.GRAY));
    }

    private void addMouseListenerToComponent(JComponent component, String componentName) {
        component.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                JDialog popup = new JDialog(SwingUtilities.getWindowAncestor(component), "Thôn tin chi tiết", Dialog.ModalityType.APPLICATION_MODAL);
                popup.getContentPane().setLayout(new BorderLayout());
                popup.getContentPane().add(new ManageEmployeeDetailInfo_Component(employee));
                popup.setSize(1120, 740);
                popup.setResizable(false);
                popup.setLocationRelativeTo(null);
                popup.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
