/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.component.EmployeeAndDepartmentInfo.DepartmentInfo;

import java.awt.Color;
import java.awt.Component;
import java.awt.Image;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JTree;
import javax.swing.SwingUtilities;
import javax.swing.border.MatteBorder;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeCellRenderer;
import javax.swing.tree.DefaultTreeModel;
import org.w3c.dom.css.CSSPrimitiveValue;
import org.w3c.dom.css.RGBColor;

/**
 *
 * @author LENOVO
 */
public class DepartmentData_Component extends javax.swing.JPanel {

    /**
     * Creates new form Department_Component
     */
    public DepartmentData_Component() {
        initComponents();

        SwingUtilities.invokeLater(() -> {
            jScrollPane1.setBorder(BorderFactory.createEmptyBorder()); // Xóa viền của JScrollPane
        });

        designTree();
        initData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        department = new javax.swing.JTree();

        setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane1.setViewportView(department);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTree department;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private void initData() {
        DefaultMutableTreeNode root = new DefaultMutableTreeNode("Root");

        // Tạo các nút con
        DefaultMutableTreeNode parent1 = new DefaultMutableTreeNode("Parent 1");
        DefaultMutableTreeNode parent2 = new DefaultMutableTreeNode("Parent 2");

        // Thêm các nút con vào Parent 1
        parent1.add(new DefaultMutableTreeNode("Child 1.1"));
        parent1.add(new DefaultMutableTreeNode("Child 1.2"));

        // Thêm các nút con vào Parent 2
        parent2.add(new DefaultMutableTreeNode("Child 2.1"));
        parent2.add(new DefaultMutableTreeNode("Child 2.2"));

        // Thêm các Parent vào nút gốc
        root.add(parent1);
        root.add(parent2);

        // Tạo mô hình mới và gán mô hình cho JTree
        DefaultTreeModel model = new DefaultTreeModel(root);
        department.setModel(model);
    }

    private void designTree() {
        DefaultTreeCellRenderer renderer = new DefaultTreeCellRenderer();

        ImageIcon icon = new ImageIcon(getClass().getResource("/icon/home.png"));

        Image scaleIcon = icon.getImage().getScaledInstance(15, 15, Image.SCALE_SMOOTH);

        renderer.setClosedIcon(new ImageIcon(scaleIcon));
        renderer.setOpenIcon(new ImageIcon(scaleIcon));
        renderer.setLeafIcon(new ImageIcon(scaleIcon));

        department.setCellRenderer(renderer);
    }

}
