/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.form.Home.Navigation;

import java.awt.FlowLayout;
import javax.swing.ImageIcon;
import javax.swing.border.EmptyBorder;
import view.form.Home.Navigation.Function_Component.Function_Component;

/**
 *
 * @author PC
 */
public class Navigation extends javax.swing.JPanel {

    /**
     * Creates new form Navigation
     */
    public Navigation() {
        initComponents();
        setLayout();
        addComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 260, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 495, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void setLayout() {
        this.setBorder(new EmptyBorder(10, 15, 10, 15));
        this.setLayout(new FlowLayout(FlowLayout.LEFT, 0, 0));
    }

    private void addComponents() {
        ImageIcon focusIcon = new ImageIcon(getClass().getResource("/icon/user2.png"));
        ImageIcon exitIcon = new ImageIcon(getClass().getResource("/icon/user1.png"));

        this.add(new Function_Component("Thông tin nhân viên", focusIcon, exitIcon));
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
