/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.form.Home.MainContent;

import java.awt.CardLayout;
import view.component.Function_Component.FunctionData_Component;
import view.component.LeaveApplication.GridLeaveRequest.GridLeaveApplication_Component;
import view.component.Manage_Component.ManageEmployeeInfo_Component;
import view.component.Salary.Salary_Component.Salary_Component;

/**
 *
 * @author LENOVO
 */
public class MainContent extends javax.swing.JPanel {

    private static MainContent instance;

    public MainContent() {
        initComponents();
        setLayout();
        addComponents();
    }

    public static MainContent getInstance() {
        if (instance == null) {
            instance = new MainContent();
        }
        return instance;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void setLayout() {
        this.setLayout(new CardLayout());
    }

    private void addComponents() {
        this.add(new FunctionData_Component(), "F0000");
        this.add(new ManageEmployeeInfo_Component(), "F0001");
        this.add(new Salary_Component(), "F0003");
        this.add(new GridLeaveApplication_Component(), "F0004");
    }

    public void changePage(String functionId) {
        CardLayout c = (CardLayout) this.getLayout();
        c.show(this, functionId);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
