/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.component.Notification.Notificaition_Component;

import java.awt.GridLayout;
import javax.swing.ImageIcon;

/**
 *
 * @author LENOVO
 */
public class ListNotification_Component extends javax.swing.JPanel {

    /**
     * Creates new form ListNotification_Component
     */
    public ListNotification_Component() {
        initComponents();
        setLayout();
        addComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void setLayout() {
        this.setLayout(new GridLayout(0, 1, 0, 0));
    }

    private void addComponents() {
        ImageIcon icon = new ImageIcon(getClass().getResource("/img/avatar.jpg"));
        String message = "<html>Đây là một đoạn thông báo dài. Khi văn bản quá dài, nó sẽ tự động xuống dòng trong JLabel.</html>";
        String time = "6:07PM 13/11/2024";
        for (int i = 1; i <= 4; i++) {
            this.add(new Notification_Component(icon, message, time));
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
