/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.component.BenefitsInfo_Component;

import java.awt.Dimension;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author user
 */
public class MaternityLeave_Component_BI extends javax.swing.JPanel {

    /**
     * Creates new form MaternityLeave_Component_BI
     */
    public MaternityLeave_Component_BI() {
        initComponents();
        this.setPreferredSize(new Dimension(1120, 350));
//        setImg();
    }

    private ImageIcon scaleImg(JLabel jLabel, String url) {
        title.setSize(20, 20);
        ImageIcon imageIcon = new ImageIcon(getClass().getResource(url));
        Image image = imageIcon.getImage();
        Image scaleImage = image.getScaledInstance(jLabel.getWidth(), jLabel.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(scaleImage);
        return scaledIcon;
    }

    private void setImg() {
        String urlTitle = "/img/infor.png";

        ImageIcon iconTitle = scaleImg(title, urlTitle);

        title.setIcon(iconTitle);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        childcareSupport_Man = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        gender_Man = new javax.swing.JLabel();
        maternityLeave_Man = new javax.swing.JLabel();
        maternityLeaveRegulations_Man = new javax.swing.JLabel();
        financialBenefits_Man = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        maNhanVien1 = new javax.swing.JLabel();
        nameEmployee = new javax.swing.JLabel();
        procedureApprover_Man = new javax.swing.JLabel();
        genderEmployee = new javax.swing.JLabel();
        birthdayEmployee = new javax.swing.JLabel();
        nameEmployee1 = new javax.swing.JLabel();
        childcareSupport_Woman = new javax.swing.JLabel();
        genderEmployee1 = new javax.swing.JLabel();
        maternityLeaveRegulations_Woman = new javax.swing.JLabel();
        birthdayEmployee1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        gender_Woman = new javax.swing.JLabel();
        maternityLeave_Woman = new javax.swing.JLabel();
        financialBenefits_Woman = new javax.swing.JLabel();
        procedureApprover_Woman = new javax.swing.JLabel();
        date1 = new javax.swing.JLabel();
        maNhanVien2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        otherbBenefits_Man = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        otherBenefits_Woman = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(255, 255, 255));

        title.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        title.setForeground(new java.awt.Color(0, 0, 255));
        title.setText("Nghỉ thai sản");

        childcareSupport_Man.setText("???");

        jLabel1.setText("Quy định nghĩ thai sản");

        gender_Man.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        gender_Man.setText("Nam");

        maternityLeave_Man.setText("????");

        maternityLeaveRegulations_Man.setText("????");

        financialBenefits_Man.setText("????");

        date.setText("Giới tính");

        maNhanVien1.setText("Hỗ trợ chăm sóc trẻ sơ sinh");

        nameEmployee.setText("Thời gian nghĩ thai sản");

        procedureApprover_Man.setText("????");

        genderEmployee.setText("Quyền lợi tài chính");

        birthdayEmployee.setText("Duyệt thủ tục nghĩ thai sản");

        nameEmployee1.setText("Thời gian nghĩ thai sản");

        childcareSupport_Woman.setText("????");

        genderEmployee1.setText("Quyền lợi tài chính");

        maternityLeaveRegulations_Woman.setText("???");

        birthdayEmployee1.setText("Duyệt thủ tục nghĩ thai sản");

        jLabel2.setText("Quy định nghĩ thai sản");

        gender_Woman.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        gender_Woman.setText("Nữ ");

        maternityLeave_Woman.setText("????");

        financialBenefits_Woman.setText("????");

        procedureApprover_Woman.setText("????");

        date1.setText("Giới tính");

        maNhanVien2.setText("Hỗ trợ chăm sóc trẻ sơ sinh");

        jLabel3.setText("Các phúc lợi khác");

        otherbBenefits_Man.setColumns(20);
        otherbBenefits_Man.setRows(5);
        otherbBenefits_Man.setText("A :\nB :\nC :");
        jScrollPane1.setViewportView(otherbBenefits_Man);

        jLabel4.setText("Các phúc lợi khác");

        otherBenefits_Woman.setColumns(20);
        otherBenefits_Woman.setRows(5);
        otherBenefits_Woman.setText("A : \nB :\nC :");
        jScrollPane2.setViewportView(otherBenefits_Woman);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(nameEmployee)
                            .addComponent(date)
                            .addComponent(genderEmployee)
                            .addComponent(birthdayEmployee1)
                            .addComponent(maNhanVien1)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(maternityLeaveRegulations_Man)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(childcareSupport_Man)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(maNhanVien2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(procedureApprover_Man)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(birthdayEmployee))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(financialBenefits_Man)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(genderEmployee1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(gender_Man)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(date1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(maternityLeave_Man)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(nameEmployee1)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(gender_Woman)
                            .addComponent(maternityLeave_Woman)
                            .addComponent(procedureApprover_Woman)
                            .addComponent(childcareSupport_Woman)
                            .addComponent(maternityLeaveRegulations_Woman)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(financialBenefits_Woman))
                        .addGap(184, 184, 184))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(title)
                        .addContainerGap(953, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(title)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(gender_Man, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(date))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(date1)
                        .addComponent(gender_Woman)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(nameEmployee)
                        .addComponent(maternityLeave_Man))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(maternityLeave_Woman)
                        .addComponent(nameEmployee1)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(genderEmployee1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(genderEmployee)
                        .addComponent(financialBenefits_Man)
                        .addComponent(financialBenefits_Woman)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(birthdayEmployee1)
                    .addComponent(procedureApprover_Man)
                    .addComponent(birthdayEmployee)
                    .addComponent(procedureApprover_Woman))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maNhanVien1)
                    .addComponent(childcareSupport_Man)
                    .addComponent(maNhanVien2)
                    .addComponent(childcareSupport_Woman))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(maternityLeaveRegulations_Man)
                    .addComponent(jLabel2)
                    .addComponent(maternityLeaveRegulations_Woman))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel birthdayEmployee;
    private javax.swing.JLabel birthdayEmployee1;
    private javax.swing.JLabel childcareSupport_Man;
    private javax.swing.JLabel childcareSupport_Woman;
    private javax.swing.JLabel date;
    private javax.swing.JLabel date1;
    private javax.swing.JLabel financialBenefits_Man;
    private javax.swing.JLabel financialBenefits_Woman;
    private javax.swing.JLabel genderEmployee;
    private javax.swing.JLabel genderEmployee1;
    private javax.swing.JLabel gender_Man;
    private javax.swing.JLabel gender_Woman;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel maNhanVien1;
    private javax.swing.JLabel maNhanVien2;
    private javax.swing.JLabel maternityLeaveRegulations_Man;
    private javax.swing.JLabel maternityLeaveRegulations_Woman;
    private javax.swing.JLabel maternityLeave_Man;
    private javax.swing.JLabel maternityLeave_Woman;
    private javax.swing.JLabel nameEmployee;
    private javax.swing.JLabel nameEmployee1;
    private javax.swing.JTextArea otherBenefits_Woman;
    private javax.swing.JTextArea otherbBenefits_Man;
    private javax.swing.JLabel procedureApprover_Man;
    private javax.swing.JLabel procedureApprover_Woman;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
