/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.component.BenefitsInfo_Component;

import java.awt.Dimension;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author user
 */
public class RemoteWork_Component_BI extends javax.swing.JPanel {

    /**
     * Creates new form RemoteWork_Component_BI
     */
    public RemoteWork_Component_BI() {
        initComponents();
        this.setPreferredSize(new Dimension(1120, 260));
//        setImg();
    }

    private ImageIcon scaleImg(JLabel jLabel, String url) {
        title.setSize(20, 20);
        ImageIcon imageIcon = new ImageIcon(getClass().getResource(url));
        Image image = imageIcon.getImage();
        Image scaleImage = image.getScaledInstance(jLabel.getWidth(), jLabel.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(scaleImage);
        return scaledIcon;
    }

    private void setImg() {
        String urlTitle = "/img/infor.png";

        ImageIcon iconTitle = scaleImg(title, urlTitle);

        title.setIcon(iconTitle);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        genderEmployee = new javax.swing.JLabel();
        workPerformanceManagement = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        businessTravelPolicy = new javax.swing.JLabel();
        workCondition = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        specificWorkHourPolicy = new javax.swing.JLabel();
        safetyAndSecurityPolicy = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        maNhanVien1 = new javax.swing.JLabel();
        nameEmployee = new javax.swing.JLabel();
        mentalHealthSupport = new javax.swing.JLabel();
        birthdayEmployee = new javax.swing.JLabel();
        nameEmployee1 = new javax.swing.JLabel();
        info_OfTheDocumentApprover = new javax.swing.JLabel();
        remoteWorkPolicy = new javax.swing.JCheckBox();

        setBackground(new java.awt.Color(255, 255, 255));

        title.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        title.setForeground(new java.awt.Color(0, 0, 255));
        title.setText("Chính sách làm việc từ xa");

        genderEmployee.setText("Chính sách an toàn và bảo mật");

        workPerformanceManagement.setText("???");

        jLabel1.setText("Quản lý hiệu suất");

        businessTravelPolicy.setText("???????");

        workCondition.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        workCondition.setText("công ty / ở nhà");

        jLabel3.setText("Chính sách đi công tác");

        specificWorkHourPolicy.setText("????");

        safetyAndSecurityPolicy.setText("????");

        date.setText("Điều kiện làm việc");

        maNhanVien1.setText("Hỗ trợ sức khỏe tâm lý");

        nameEmployee.setText("Chính sách về giờ làm cụ thể");

        mentalHealthSupport.setText("????");

        birthdayEmployee.setText("Duyệt chính sách làm việc từ xa");

        nameEmployee1.setText("Thông tin người duyệt ");

        info_OfTheDocumentApprover.setText("????");

        remoteWorkPolicy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                remoteWorkPolicyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(title))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(nameEmployee)
                            .addComponent(date)
                            .addComponent(genderEmployee)
                            .addComponent(maNhanVien1)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(workCondition)
                                        .addGap(315, 315, 315)
                                        .addComponent(nameEmployee1))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(specificWorkHourPolicy)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(birthdayEmployee)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(info_OfTheDocumentApprover)
                                    .addComponent(remoteWorkPolicy)))
                            .addComponent(safetyAndSecurityPolicy)
                            .addComponent(mentalHealthSupport)
                            .addComponent(workPerformanceManagement)
                            .addComponent(businessTravelPolicy))))
                .addContainerGap(277, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(title)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(date)
                            .addComponent(workCondition)
                            .addComponent(nameEmployee1)
                            .addComponent(info_OfTheDocumentApprover))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nameEmployee)
                            .addComponent(specificWorkHourPolicy)
                            .addComponent(birthdayEmployee)))
                    .addComponent(remoteWorkPolicy))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(genderEmployee)
                    .addComponent(safetyAndSecurityPolicy))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maNhanVien1)
                    .addComponent(mentalHealthSupport))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(workPerformanceManagement))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(businessTravelPolicy))
                .addContainerGap(29, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void remoteWorkPolicyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_remoteWorkPolicyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_remoteWorkPolicyActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel birthdayEmployee;
    private javax.swing.JLabel businessTravelPolicy;
    private javax.swing.JLabel date;
    private javax.swing.JLabel genderEmployee;
    private javax.swing.JLabel info_OfTheDocumentApprover;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel maNhanVien1;
    private javax.swing.JLabel mentalHealthSupport;
    private javax.swing.JLabel nameEmployee;
    private javax.swing.JLabel nameEmployee1;
    private javax.swing.JCheckBox remoteWorkPolicy;
    private javax.swing.JLabel safetyAndSecurityPolicy;
    private javax.swing.JLabel specificWorkHourPolicy;
    private javax.swing.JLabel title;
    private javax.swing.JLabel workCondition;
    private javax.swing.JLabel workPerformanceManagement;
    // End of variables declaration//GEN-END:variables
}
