/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.component.Salary.Salary_Component.Data;

import controller.DAO.AttendanceRecordsDAO;
import controller.DAO.SalaryDAO;
import controller.DAOImp.AttendanceRecordsDAOImp;
import controller.DAOImp.SalaryDAOImp;
import view.component.Salary.Salary_Component.Title.*;
import java.awt.GridLayout;
import java.time.LocalDate;
import java.util.List;
import model.AttendanceRecords;
import model.Employee;
import model.PayPeriod;
import model.Salary;
import org.hibernate.Hibernate;
import org.hibernate.Session;
import util.HibernateUtil;

/**
 *
 * @author LENOVO
 */
public class Data_Container extends javax.swing.JPanel {

    /**
     * Creates new form Date_Container
     */
    public Data_Container() {
        initComponents();
        setLayout();
        addComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 840, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    private void setLayout() {
        this.setLayout(new GridLayout(0, 5, 0, 0));
    }

    private void addComponents() {
        for (int i = 1; i <= 40; i++) {
            this.add(new Data_Component("20.000.000"));
        }
    }

    public void updateData(Employee employee, PayPeriod period) {
        try (Session session = HibernateUtil.getSessionFactory().openSession()) {
            SalaryDAO salaryDAO = new SalaryDAOImp(session);
            AttendanceRecordsDAO attendanceRecordsDAO = new AttendanceRecordsDAOImp(session);

            Salary salary = salaryDAO.getByEmployeeAndPayPeriod(employee, period);

            String baseSalary = employee.getContracts().get(0).getBaseSalary() + "";
            String title = employee.getRoleDetail().getRole().getName();
            String starndardKOW = "200W";
            List<AttendanceRecords> attendanceRecordsList = attendanceRecordsDAO.getByAttendanceInformationAndPayPeriod(employee.getAttendanceInformation(), period.getStartDate(), period.getEndDate());
            String totalKow = attendanceRecordsList.stream()
                    .mapToDouble(AttendanceRecords::getKow)
                    .sum() + "";
            String salaryValue = salary.getSalary() + "";

            this.add(new Data_Component(baseSalary));
            this.add(new Data_Component(title));
            this.add(new Data_Component(starndardKOW));
            this.add(new Data_Component(totalKow));
            this.add(new Data_Component(salaryValue));
            revalidate();
            repaint();
        } catch (Exception e) {
            System.out.println(e);
        }

    }
}
