package view.component.EmployeeDetailInfo.PersonalProfile_Component;


import java.awt.Dimension;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
/**
 *
 * @author user
 */
public class PersonalProfile extends javax.swing.JPanel {

    /**
     * Creates new form PersonalProfile
     */
    public PersonalProfile() {
        initComponents();
        this.setPreferredSize(new Dimension(1120, 240));
        setImg();
    }

    private ImageIcon scaleImg(JLabel jLabel, String url) {
        title.setSize(20,20);
        ImageIcon imageIcon = new ImageIcon(getClass().getResource(url));
        Image image = imageIcon.getImage();
        Image scaleImage = image.getScaledInstance(jLabel.getWidth(), jLabel.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(scaleImage);
        return scaledIcon;
    }

    private void setImg() {
        String urlTitle = "/img/infor.png";

        ImageIcon iconTitle = scaleImg(title, urlTitle);

        title.setIcon(iconTitle);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        idEmployee = new javax.swing.JLabel();
        input_idEmployee = new javax.swing.JLabel();
        input_MaNhanVien1 = new javax.swing.JLabel();
        maNhanVien1 = new javax.swing.JLabel();
        input_NameEmployee = new javax.swing.JLabel();
        nameEmployee = new javax.swing.JLabel();
        input_GenderEmployee = new javax.swing.JLabel();
        genderEmployee = new javax.swing.JLabel();
        input_MaNhanVien4 = new javax.swing.JLabel();
        maNhanVien4 = new javax.swing.JLabel();
        input_MaNhanVien5 = new javax.swing.JLabel();
        maNhanVien5 = new javax.swing.JLabel();
        input_MaNhanVien6 = new javax.swing.JLabel();
        maNhanVien6 = new javax.swing.JLabel();
        birthdayEmployee = new javax.swing.JLabel();
        input_BirthdayEmployee = new javax.swing.JLabel();
        maNhanVien8 = new javax.swing.JLabel();
        input_MaNhanVien8 = new javax.swing.JLabel();
        maNhanVien9 = new javax.swing.JLabel();
        input_MaNhanVien9 = new javax.swing.JLabel();
        maNhanVien10 = new javax.swing.JLabel();
        input_MaNhanVien10 = new javax.swing.JLabel();
        maNhanVien11 = new javax.swing.JLabel();
        input_MaNhanVien11 = new javax.swing.JLabel();
        maNhanVien12 = new javax.swing.JLabel();
        input_MaNhanVien12 = new javax.swing.JLabel();
        maNhanVien13 = new javax.swing.JLabel();
        input_MaNhanVien13 = new javax.swing.JLabel();
        maNhanVien14 = new javax.swing.JLabel();
        input_MaNhanVien14 = new javax.swing.JLabel();
        maNhanVien15 = new javax.swing.JLabel();
        input_MaNhanVien15 = new javax.swing.JLabel();
        maNhanVien16 = new javax.swing.JLabel();
        input_MaNhanVien16 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1120, 240));

        title.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        title.setForeground(new java.awt.Color(0, 0, 255));
        title.setText("Thông tin cá nhân");

        idEmployee.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        idEmployee.setText("Mã nhân viên");

        input_idEmployee.setText("jLabel1");

        input_MaNhanVien1.setText("jLabel1");

        maNhanVien1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        maNhanVien1.setText("Dân tộc");

        input_NameEmployee.setText("jLabel1");

        nameEmployee.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        nameEmployee.setText("Tên nhân viên");

        input_GenderEmployee.setText("jLabel1");

        genderEmployee.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        genderEmployee.setText("Giới tính");

        input_MaNhanVien4.setText("jLabel1");

        maNhanVien4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        maNhanVien4.setText("Quốc tịch");

        input_MaNhanVien5.setText("jLabel1");

        maNhanVien5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        maNhanVien5.setText("Tôn giáo");

        input_MaNhanVien6.setText("jLabel1");

        maNhanVien6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        maNhanVien6.setText("Tình trạng hôn nhân");

        birthdayEmployee.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        birthdayEmployee.setText("Ngày sinh");

        input_BirthdayEmployee.setText("jLabel1");

        maNhanVien8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        maNhanVien8.setText("Chuyên ngành");

        input_MaNhanVien8.setText("jLabel1");

        maNhanVien9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        maNhanVien9.setText("Số CCCD");

        input_MaNhanVien9.setText("jLabel1");

        maNhanVien10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        maNhanVien10.setText("Mã số thuế");

        input_MaNhanVien10.setText("jLabel1");

        maNhanVien11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        maNhanVien11.setText("Ngày cấp CCCD");

        input_MaNhanVien11.setText("jLabel1");

        maNhanVien12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        maNhanVien12.setText("Nơi cấp CCCD");

        input_MaNhanVien12.setText("jLabel1");

        maNhanVien13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        maNhanVien13.setText("Trình độ văn hóa");

        input_MaNhanVien13.setText("jLabel1");

        maNhanVien14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        maNhanVien14.setText("Trình độ học vấn");

        input_MaNhanVien14.setText("jLabel1");

        maNhanVien15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        maNhanVien15.setText("Ngày cấp mã số thuế");

        input_MaNhanVien15.setText("jLabel1");

        maNhanVien16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        maNhanVien16.setText("Nơi cấp mã số thuế");

        input_MaNhanVien16.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(title)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(input_MaNhanVien16)
                            .addComponent(maNhanVien16))
                        .addGap(72, 72, 72)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(input_MaNhanVien15)
                            .addComponent(maNhanVien15))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(input_MaNhanVien8)
                            .addComponent(maNhanVien8)
                            .addComponent(input_MaNhanVien10)
                            .addComponent(maNhanVien10)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(input_idEmployee)
                            .addComponent(idEmployee))))
                .addGap(94, 94, 94)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(input_NameEmployee)
                    .addComponent(nameEmployee)
                    .addComponent(input_MaNhanVien14)
                    .addComponent(maNhanVien14))
                .addGap(85, 85, 85)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(input_MaNhanVien13)
                    .addComponent(maNhanVien13)
                    .addComponent(input_GenderEmployee)
                    .addComponent(genderEmployee))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(input_BirthdayEmployee)
                            .addComponent(birthdayEmployee))
                        .addGap(100, 100, 100))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(input_MaNhanVien6)
                            .addComponent(maNhanVien6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(input_MaNhanVien1)
                    .addComponent(maNhanVien1)
                    .addComponent(input_MaNhanVien9)
                    .addComponent(maNhanVien9))
                .addGap(96, 96, 96)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(input_MaNhanVien4)
                    .addComponent(maNhanVien4)
                    .addComponent(input_MaNhanVien11)
                    .addComponent(maNhanVien11))
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(input_MaNhanVien5)
                    .addComponent(maNhanVien5)
                    .addComponent(maNhanVien12)
                    .addComponent(input_MaNhanVien12))
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(idEmployee)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(input_idEmployee))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nameEmployee)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(input_NameEmployee))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(genderEmployee)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(input_GenderEmployee))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(birthdayEmployee)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(input_BirthdayEmployee))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(maNhanVien1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(input_MaNhanVien1))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(maNhanVien4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(input_MaNhanVien4)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(maNhanVien8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(input_MaNhanVien8))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(maNhanVien14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(input_MaNhanVien14)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(maNhanVien10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(input_MaNhanVien10))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(maNhanVien16)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(input_MaNhanVien16))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(maNhanVien15)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(input_MaNhanVien15)))
                                .addGap(17, 17, 17))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(maNhanVien12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(input_MaNhanVien12))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(maNhanVien11)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(input_MaNhanVien11)
                                            .addContainerGap())
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(maNhanVien13)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(input_MaNhanVien13))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(maNhanVien6)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(input_MaNhanVien6))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(maNhanVien9)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(input_MaNhanVien9)))
                                            .addGap(84, 84, 84)))))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(maNhanVien5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(input_MaNhanVien5)
                        .addGap(3, 156, Short.MAX_VALUE))))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel birthdayEmployee;
    private javax.swing.JLabel genderEmployee;
    private javax.swing.JLabel idEmployee;
    private javax.swing.JLabel input_BirthdayEmployee;
    private javax.swing.JLabel input_GenderEmployee;
    private javax.swing.JLabel input_MaNhanVien1;
    private javax.swing.JLabel input_MaNhanVien10;
    private javax.swing.JLabel input_MaNhanVien11;
    private javax.swing.JLabel input_MaNhanVien12;
    private javax.swing.JLabel input_MaNhanVien13;
    private javax.swing.JLabel input_MaNhanVien14;
    private javax.swing.JLabel input_MaNhanVien15;
    private javax.swing.JLabel input_MaNhanVien16;
    private javax.swing.JLabel input_MaNhanVien4;
    private javax.swing.JLabel input_MaNhanVien5;
    private javax.swing.JLabel input_MaNhanVien6;
    private javax.swing.JLabel input_MaNhanVien8;
    private javax.swing.JLabel input_MaNhanVien9;
    private javax.swing.JLabel input_NameEmployee;
    private javax.swing.JLabel input_idEmployee;
    private javax.swing.JLabel maNhanVien1;
    private javax.swing.JLabel maNhanVien10;
    private javax.swing.JLabel maNhanVien11;
    private javax.swing.JLabel maNhanVien12;
    private javax.swing.JLabel maNhanVien13;
    private javax.swing.JLabel maNhanVien14;
    private javax.swing.JLabel maNhanVien15;
    private javax.swing.JLabel maNhanVien16;
    private javax.swing.JLabel maNhanVien4;
    private javax.swing.JLabel maNhanVien5;
    private javax.swing.JLabel maNhanVien6;
    private javax.swing.JLabel maNhanVien8;
    private javax.swing.JLabel maNhanVien9;
    private javax.swing.JLabel nameEmployee;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
