package view.component.EmployeeDetailInfo.PersonalProfile_Component;


import java.awt.BorderLayout;
import java.awt.Dimension;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
/**
 *
 * @author user
 */
public class PersonProfile_Hotline_Title_Container extends javax.swing.JPanel {

    /**
     * Creates new form PersonProfile_Hotline_Title_Container
     */
    public PersonProfile_Hotline_Title_Container() {
        initComponents();
        this.setPreferredSize(new Dimension(900, 545));
        setLayout();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1120, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 545, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void setLayout() {  
         this.setLayout(new BorderLayout());
         PersonalProfile_Hotline_Container personalProfile_Hotline = new PersonalProfile_Hotline_Container();
         TitleRight_Component title = new TitleRight_Component();
         this.add(title, BorderLayout.NORTH);
         this.add(personalProfile_Hotline, BorderLayout.CENTER);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
