package view.component.EmployeeDetailInfo.PersonalProfile_Component;


import java.awt.BorderLayout;
import java.awt.Dimension;
import view.component.EmployeeDetailInfo.PersonalProfile_Component.Hotline_Component;
import view.component.EmployeeDetailInfo.PersonalProfile_Component.PersonalProfile;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author user
 */
public class PersonalProfile_Hotline_Container extends javax.swing.JPanel {

    /**
     * Creates new form PersonalProfile_Hotline_Container
     */
    public PersonalProfile_Hotline_Container() {
        initComponents();
        this.setPreferredSize(new Dimension(900, 490));
        setLayout();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1120, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 490, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void setLayout() {
        this.setLayout(new BorderLayout());
        PersonalProfile personalProfile = new PersonalProfile();
        Hotline_Component hotline = new Hotline_Component();
        this.add(personalProfile, BorderLayout.NORTH);
        this.add(hotline, BorderLayout.CENTER);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
